// Generated by CoffeeScript 1.6.2
(function() {
  var RemoteLauncher, Url, asyngleton, cstep, dnode,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  dnode = require("dnode");

  cstep = require("cstep");

  Url = require("url");

  asyngleton = require("asyngleton");

  RemoteLauncher = (function(_super) {
    __extends(RemoteLauncher, _super);

    /*
    */


    function RemoteLauncher(address) {
      RemoteLauncher.__super__.constructor.call(this);
      if (!~address.indexOf("://")) {
        address = "http://" + address;
      }
      this.address = Url.parse(address);
    }

    /*
    */


    RemoteLauncher.prototype.load = asyngleton(cstep(function(callback) {
      var d,
        _this = this;

      d = dnode();
      d.on("remote", function(client) {
        _this.client = client;
        return callback();
      });
      return d.connect(this.address.port, this.address.hostname);
    }));

    /*
    */


    RemoteLauncher.prototype.test = function(options, callback) {
      var _this = this;

      return this.load(function() {
        return _this.client.test(options, callback);
      });
    };

    /*
    */


    RemoteLauncher.prototype.start = function(options, callback) {
      var _this = this;

      return this.load(function() {
        return _this.client.start(options, callback);
      });
    };

    return RemoteLauncher;

  })(require("../base"));

  module.exports = RemoteLauncher;

}).call(this);
