// Generated by CoffeeScript 1.6.2
(function() {
  var Factory, available, toarray;

  toarray = require("toarray");

  available = {
    local: require("./local"),
    remote: require("./remote")
  };

  Factory = (function() {
    function Factory() {}

    /*
    */


    Factory.prototype.getLaunchers = function(options) {
      var clazz, inst, launchers, o, ops, type, _i, _len;

      launchers = [];
      for (type in options) {
        ops = toarray(options[type]);
        for (_i = 0, _len = ops.length; _i < _len; _i++) {
          o = ops[_i];
          clazz = available[type];
          launchers.push(inst = new clazz(o));
          inst.name = type;
        }
      }
      return launchers;
    };

    return Factory;

  })();

  module.exports = new Factory();

}).call(this);
