// Generated by CoffeeScript 1.6.2
(function() {
  var Factory, available;

  available = {
    local: require("./local"),
    remote: require("./remote")
  };

  Factory = (function() {
    function Factory() {}

    /*
    */


    Factory.prototype.getLaunchers = function(options) {
      var clazz, launchers, type;

      launchers = [];
      for (type in options) {
        clazz = available[type];
        launchers.push(new clazz(options[type]));
      }
      return launchers;
    };

    return Factory;

  })();

  module.exports = new Factory();

}).call(this);
