// Generated by CoffeeScript 1.6.2
(function() {
  var BrowserLauncher, async, factory, flatten, outcome;

  async = require("async");

  flatten = require("flatten");

  factory = require("./factory");

  outcome = require("outcome");

  /*
  */


  BrowserLauncher = (function() {
    /*
    */
    function BrowserLauncher(options) {
      this._launchers = factory.getLaunchers(options);
    }

    /*
     starts a browser
    */


    BrowserLauncher.prototype.start = function(options, callback) {
      var ops;

      if (callback == null) {
        callback = (function() {});
      }
      ops = this._fixOptions(options);
      return async.eachSeries(this._launchers, (function(launcher, next) {
        return launcher.start(ops, function(err) {
          if (err == null) {
            return callback.apply(null, arguments);
          }
          return next();
        });
      }), function() {
        return callback(new Error("" + ops.name + "@" + ops.version + " does not exist"));
      });
    };

    /*
     lists available browsers
    */


    BrowserLauncher.prototype.listBrowsers = function(callback) {
      return async.map(this._launchers, (function(launcher, next) {
        return launcher.listBrowsers(next);
      }), outcome.e(callback).s(function(result) {
        return callback(null, flatten(result));
      }));
    };

    /*
    */


    BrowserLauncher.prototype._fixOptions = function(options) {
      var nameParts;

      nameParts = options.name.split("@");
      return {
        name: nameParts.shift(),
        version: options.version || nameParts.shift() || "latest",
        args: options.args || []
      };
    };

    return BrowserLauncher;

  })();

  module.exports = BrowserLauncher;

}).call(this);
