// Generated by CoffeeScript 1.6.2
(function() {
  var Client, Server, dnode, dsync;

  Client = require("../client");

  dnode = require("dnode");

  dsync = require("dsync");

  Server = (function() {
    /*
    */
    function Server(config) {
      this.client = new Client(config);
    }

    /*
    */


    Server.prototype.listen = function(port) {
      console.log("listening on port " + port);
      dnode(dsync(this.client)).listen(port);
      return this;
    };

    /*
    */


    Server.prototype.use = function() {
      var _ref;

      return (_ref = this.client).use.apply(_ref, arguments);
    };

    return Server;

  })();

  module.exports = Server;

}).call(this);
