// Generated by CoffeeScript 1.6.2
(function() {
  var Launcher;

  require("coffee-script");

  Launcher = require("./launcher");

  module.exports = Launcher;

  module.exports.plugins = require("./plugins");

}).call(this);
