// Generated by CoffeeScript 1.6.2
(function() {
  var async, exec, platform;

  async = require("async");

  exec = require("child_process").exec;

  platform = require("os").platform();

  exports.killProcesses = function(processNames, callback) {
    return async.forEach(processNames, (function(name, next) {
      var command;

      if (/^win/.test(platform)) {
        command = "taskkill /F /IM " + name;
      } else {
        command = "killall \"" + name + "\" QUIT -9";
      }
      exports.logger.log(command);
      return exec(command, function() {
        return setTimeout(callback, 1000);
      });
    }), callback);
  };

  if (!process.env.APUPPET_LOG) {
    exports.logger = {
      warn: function() {},
      error: function() {},
      log: function() {}
    };
  } else {
    exports.logger = console;
  }

}).call(this);
