// Generated by CoffeeScript 1.6.2
(function() {
  var Version, path;

  path = require("path");

  Version = (function() {
    /*
    */
    function Version(options) {
      this.options = options;
      this.number = options.number;
      this.path = options.path;
      this.settings = options.settingDirs || [];
    }

    return Version;

  })();

  module.exports = Version;

}).call(this);
