// Generated by CoffeeScript 1.6.2
(function() {
  var BaseLoader;

  BaseLoader = (function() {
    function BaseLoader() {}

    /*
    */


    BaseLoader.prototype.test = function(options) {
      return false;
    };

    /*
    */


    BaseLoader.prototype.loadApplications = function(callback) {};

    return BaseLoader;

  })();

  module.exports = BaseLoader;

}).call(this);
