// Generated by CoffeeScript 1.6.2
(function() {
  var Url, chunnel, dns, winston;

  chunnel = require("chunnel");

  dns = require("dns");

  Url = require("url");

  winston = require("winston");

  exports.client = function(port) {
    if (port == null) {
      port = 9526;
    }
    return function(launcher) {
      var clients;

      clients = {};
      return launcher.pre("start", function(next, options) {
        var url, urlParts;

        if (!options.args.length) {
          return next();
        }
        url = options.args[0];
        if (!~url.indexOf("://")) {
          url = "http://" + url;
        }
        urlParts = Url.parse(url);
        return dns.resolve4(urlParts.hostname, function(err, addresses) {
          var client;

          if (!err && (addresses[0] !== "127.0.0.1")) {
            return next();
          }
          if (clients[url]) {
            return next();
          }
          client = clients[url] = chunnel.client.connect({
            proxy: url,
            domain: url,
            server: launcher.address.hostname + ":" + port
          });
          return client.once("connected", next);
        });
      });
    };
  };

  exports.server = function(port) {
    if (port == null) {
      port = 9526;
    }
    return chunnel.server({}).listen(port);
  };

}).call(this);
