// Generated by CoffeeScript 1.6.2
/*
 synchronizes user interactions between browsers
*/


(function() {
  var _this = this;

  exports.client = function() {
    return function(launcher) {
      return launcher.pre("start", function(next, options) {});
    };
  };

}).call(this);
