// Generated by CoffeeScript 1.6.2
(function() {
  var file, fp, fs, name, path, _i, _len, _ref;

  fs = require("fs");

  path = require("path");

  _ref = fs.readdirSync(__dirname);
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    file = _ref[_i];
    if (/\.DS_Store|index/.test(file)) {
      continue;
    }
    fp = path.basename(file).split(".");
    name = fp.shift();
    exports[name] = require(__dirname + "/" + name);
  }

}).call(this);
