// Generated by CoffeeScript 1.6.2
(function() {
  var exec, fs;

  fs = require("fs");

  exec = require("child_process").exec;

  module.exports = function(launcher) {
    return launcher.pre("start", function(next, options) {
      var address, command, rdpFilePath;

      rdpFilePath = "/tmp/eyebrowse.rdp";
      address = launcher.address.hostname;
      fs.writeFileSync(rdpFilePath, "auto connect:i:1\nfull address:s:" + address + "\nusername:s:Administrator    ", "utf8");
      exec(command = "sudo open \"/Applications/Remote Desktop Connection.app\" --args " + rdpFilePath);
      console.log(command);
      return next();
    });
  };

}).call(this);
