// Generated by CoffeeScript 1.6.2
(function() {
  var APuppet, Loader, cstep;

  require("coffee-script");

  cstep = require("cstep");

  Loader = require("./loaders");

  APuppet = (function() {
    /*
    */
    function APuppet(options) {
      this._loader = new Loader(options);
      this.load();
    }

    /*
    */


    APuppet.prototype.start = cstep(function(options, callback) {
      return loader.start(options, callback);
    });

    /*
    */


    APuppet.prototype.load = cstep(function(callback) {
      return this._loader.loadApplications(callback);
    });

    return APuppet;

  })();

  module.exports = function(options) {
    return new APuppet(options);
  };

}).call(this);
