// Generated by CoffeeScript 1.6.2
(function() {
  var RemoteLoader,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  RemoteLoader = (function(_super) {
    __extends(RemoteLoader, _super);

    /*
    */


    function RemoteLoader(url) {
      this.url = url;
    }

    /*
    */


    RemoteLoader.prototype.loadApplications = function(callback) {};

    /*
    */


    RemoteLoader.prototype.start = function(options, callback) {};

    return RemoteLoader;

  })(require("../base"));

  module.exports = RemoteLoader;

}).call(this);
