// Generated by CoffeeScript 1.6.2
(function() {
  var Version, path;

  path = require("path");

  Version = (function() {
    /*
    */
    function Version(options) {
      var pt;

      this.options = options;
      this.number = options.number;
      this.path = options.path;
      this.settings = [];
      for (pt in options.settings) {
        this.settings.push({
          from: path.join(options.settingsDirectory, pt),
          to: options.settings[pt].replace("~", process.env.HOME)
        });
      }
    }

    return Version;

  })();

  module.exports = Version;

}).call(this);
