// Generated by CoffeeScript 1.6.2
(function() {
  var Launcher, hooks, _;

  hooks = require("hooks");

  _ = require("underscore");

  Launcher = (function() {
    /*
    */
    function Launcher() {
      _.extend(this, hooks);
      this.hook("start", this.start);
      this.hook("load", this.load);
    }

    /*
    */


    Launcher.prototype.start = function() {};

    Launcher.prototype.load = function() {};

    Launcher.prototype.test = function() {};

    /*
    */


    Launcher.prototype.use = function(module) {
      return module(this);
    };

    return Launcher;

  })();

  module.exports = Launcher;

}).call(this);
