// Generated by CoffeeScript 1.6.2
(function() {
  var Launcher, hook, _;

  hook = require("../utils/hook");

  _ = require("underscore");

  Launcher = (function() {
    /*
    */
    function Launcher() {
      hook(this, "start");
      hook(this, "load");
    }

    /*
    */


    Launcher.prototype.start = function() {};

    Launcher.prototype.load = function() {};

    Launcher.prototype.test = function() {};

    /*
    */


    Launcher.prototype.use = function(module) {
      return module(this);
    };

    return Launcher;

  })();

  module.exports = Launcher;

}).call(this);
