// Generated by CoffeeScript 1.6.2
(function() {
  var async, setupHooks, type;

  async = require("async");

  type = require("type-component");

  setupHooks = function(target) {
    target.__hooks = {};
    return target.pre = function(property, fn) {
      return target.__hooks[property].pre.push(fn);
    };
  };

  module.exports = function(target, property) {
    var hooks;

    if (!target.__hooks) {
      setupHooks(target);
    }
    target.__hooks[property] = hooks = {
      call: target[property],
      pre: [],
      post: []
    };
    return target[property] = function() {
      var args, next;

      args = Array.prototype.slice.call(arguments, 0);
      if (type(args[args.length - 1]) === "function") {
        next = args[args.length - 1];
      } else {
        next = function() {};
      }
      return async.eachSeries(hooks.pre, (function(fn, next) {
        return fn.apply(target, [next].concat(args));
      }), function(err) {
        if (err != null) {
          return next(err);
        }
        return hooks.call.apply(target, args);
      });
    };
  };

}).call(this);
